group = com.github.georgenady.androidapigraph
version = 1.1.7

# Allocate 4GB to 8GB for the Gradle Daemon during compilation
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m

# Recommended performance flags for IntelliJ plugin builds
org.gradle.caching=true
# Enable Gradle Build Cache -> https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.parallel=true

pluginRepositoryUrl = https://github.com/GeorgeNady/android_api_graph

# Opt-out flag for bundling Kotlin standard library -> https://jb.gg/intellij-platform-kotlin-stdlib
kotlin.stdlib.default.dependency = false

# Enable Gradle Configuration Cache -> https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache = true

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
